In [1]:
import sys
print(sys.executable)
sys.version

/Users/madkins/.pyenv/versions/3.8.16/envs/snowpark/bin/python3.8

'3.8.16 (default, Mar  2 2023, 19:32:24) \n[Clang 14.0.0 (clang-1400.0.29.202)]'

In [2]:
from datetime import timedelta
from getpass import getpass
import json

import numpy as np
import pandas as pd
import pyarrow as pa

from snowflake.snowpark.session import Session
from snowflake.snowpark.functions import sproc

print('Numpy version: ' + np.__version__)
print('Pandas version: ' + pd.__version__)
print('PyArrow version: ' + pa.__version__)

import pykx as kx
print('PyKX version: ' + kx.__version__)
kx.q('\c 15 120');

Numpy version: 1.23.5
Pandas version: 1.5.3
PyArrow version: 8.0.0

ModuleNotFoundError: No module named 'pykx'

In [3]:
accountname = 'xe85544.east-us-2.azure'
username = 'kx'
password = getpass('Password:')
license = getpass('License (base64):')

connection_parameters = {
    "account": accountname,
    "user": username,
    "password": password,
    "role": "SYSADMIN",
    "database": "KX",
    "schema": "BRUNO",
    "warehouse": "KX_OPT"
}

session = Session.builder.configs(connection_parameters).create()

Password:········

In [4]:
%%time

session.table('trades').count()

CPU times: user 278 µs, sys: 10.6 ms, total: 10.9 ms
Wall time: 936 ms

77026358

In [5]:
session.table('trades').limit(10).to_pandas()

,Time,Exchange,Symbol,Sale Condition,Trade Volume,Trade Price,Trade Stop Stock Indicator,Trade Correction Indicator,Sequence Number,Trade Id,Source of Trade,Trade Reporting Facility,Participant Timestamp,Trade Reporting Facility TRF Timestamp,Trade Through Exempt Indicator,TTime
0,154353684784128,D,RLX,,200,1.000,N,0,3680322,71697083422033,C,T,154353683394424,154353684434783,0,2022-10-03 15:43:53.684784128
1,154353685029888,D,RLX,,100,1.000,N,0,3680323,71697083422034,C,T,154353683505611,154353684680900,0,2022-10-03 15:43:53.685029888
2,154353685170176,D,RLX,,100,1.000,N,0,3680324,71697083422035,C,T,154353683612363,154353684817910,0,2022-10-03 15:43:53.685170176
3,154353685505792,D,RLX,,1500,1.000,N,0,3680325,71697083422037,C,T,154353683818311,154353685154683,0,2022-10-03 15:43:53.685505792
4,154353685681408,D,RLX,,300,1.000,N,0,3680326,79372242666565,C,N,154353683263494,154353685658105,0,2022-10-03 15:43:53.685681408
5,154353689901312,Z,RLX,I,35,1.005,N,0,3680327,52983526080817,C,None,154353689662000,None,0,2022-10-03 15:43:53.689901312
6,154353692241920,D,RLX,,563,1.005,N,0,3680328,71697083422256,C,T,154353691230000,154353691893068,0,2022-10-03 15:43:53.692241920
7,154355842427392,D,RLX,,100,1.000,N,0,3680814,71697083544392,C,T,154355840707000,154355842061689,0,2022-10-03 15:43:55.842427392
8,154355843088896,D,RLX,,100,1.000,N,0,3680815,71697083544393,C,T,154355840707000,154355842739671,0,2022-10-03 15:43:55.843088896
9,154355843349504,D,RLX,,100,1.000,N,0,3680816,71697083544394,C,T,154355840708000,154355842998520,0,2022-10-03 15:43:55.843349504

In [6]:
%%time

session.table('quotes').count()

CPU times: user 9.06 ms, sys: 0 ns, total: 9.06 ms
Wall time: 429 ms

1541781424

In [7]:
session.table('quotes').limit(10).to_pandas()

,Time,Exchange,Symbol,Bid_Price,Bid_Size,Offer_Price,Offer_Size,Quote_Condition,Sequence_Number,National_BBO_Ind,...,Retail_Interest_Indicator,Short_Sale_Restriction_Indicator,LULD_BBO_Indicator,SIP_Generated_Message_Identifier,National_BBO_LULD_Indicator,Participant_Timestamp,FINRA_ADF_Timestamp,FINRA_ADF_Market_Participant_Quote_Indicator,Security_Status_Indicator,TTime
0,155103751859200,T,KO,56.68,3.0,56.69,21.0,R,51615578.0,A,...,None,None,None,None,A,155103751517121,None,None,,2022-10-03 15:51:03.751859200
1,155103751859200,X,KO,56.67,1.0,56.69,1.0,R,51615579.0,A,...,None,None,None,None,A,155103751517674,None,None,,2022-10-03 15:51:03.751859200
2,155103751879680,T,KO,56.68,3.0,56.69,22.0,R,51615581.0,A,...,None,None,None,None,A,155103751540394,None,None,,2022-10-03 15:51:03.751879680
3,155103751884288,X,KO,56.67,1.0,56.69,2.0,R,51615582.0,A,...,None,None,None,None,A,155103751541114,None,None,,2022-10-03 15:51:03.751884288
4,155103751894272,T,KO,56.68,3.0,56.69,23.0,R,51615583.0,A,...,None,None,None,None,A,155103751551772,None,None,,2022-10-03 15:51:03.751894272
5,155103751909376,T,KO,56.68,3.0,56.69,20.0,R,51615584.0,A,...,None,None,None,None,A,155103751569984,None,None,,2022-10-03 15:51:03.751909376
6,155103751919360,H,KO,56.67,1.0,56.69,5.0,R,51615585.0,A,...,None,None,None,None,A,155103751464650,None,None,,2022-10-03 15:51:03.751919360
7,155103752164864,T,KO,56.68,2.0,56.69,20.0,R,51615588.0,A,...,None,None,None,None,A,155103751820947,None,None,,2022-10-03 15:51:03.752164864
8,155103752185088,T,KO,56.68,2.0,56.69,23.0,R,51615589.0,A,...,None,None,None,None,A,155103751841036,None,None,,2022-10-03 15:51:03.752185088
9,155103752195072,T,KO,56.68,2.0,56.69,25.0,R,51615590.0,A,...,None,None,None,None,A,155103751855616,None,None,,2022-10-03 15:51:03.752195072

In [8]:
%%time

def business_logic(t, q):
    from datetime import timedelta

    q['mid'] = (q['ask_price'] + q['bid_price']) / 2
    qq = q[['symbol', 'time', 'mid']]

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(seconds=1)
    t['tp1s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(seconds=5)
    t['tp5s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(seconds=10)
    t['tp10s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(minutes=1)
    t['tp1m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(minutes=5)
    t['tp5m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(minutes=10)
    t['tp10m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] += timedelta(minutes=30)
    t['tp30m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']


    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(seconds=1)
    t['tm1s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(seconds=5)
    t['tm5s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(seconds=10)
    t['tm10s'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']
    
    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(minutes=1)
    t['tm1m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(minutes=5)
    t['tm5m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(minutes=10)
    t['tm10m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    tt = t[['symbol', 'time']].copy()
    tt['time'] -= timedelta(minutes=30)
    t['tm30m'] = pd.merge_asof(tt, qq, on='time', by='symbol')['mid']

    t['time'] = t['time'].astype('uint64')

    return t


@sproc(packages=['snowflake-snowpark-python', 'numpy', 'pandas', 'pyarrow'])
def my_pandas_procedure(session: Session) -> str:
    import json, time
    
    tstart = time.perf_counter()
    select_columns = ['"TTime"', '"Symbol"', '"Trade Volume"', '"Trade Price"']
    trades = session.table('trades').select(select_columns).order_by('"TTime"').to_pandas()
    trades.columns = ['time', 'symbol', 'volume', 'price']
    tend = time.perf_counter()
    tloadtrades = tend - tstart

    tstart = time.perf_counter()
    select_columns = ['"TTime"', '"Symbol"', '"Bid_Size"', '"Bid_Price"', '"Offer_Size"', '"Offer_Price"']
    quotes = session.table('quotes').select(select_columns).order_by('"TTime"').to_pandas()
    quotes.columns = ['time', 'symbol', 'ask_volume', 'ask_price', 'bid_volume', 'bid_price']
    tend = time.perf_counter()
    tloadquotes = tend - tstart

    tstart = time.perf_counter()
    output = business_logic(trades, quotes)
    tend = time.perf_counter()
    tpdalgo = tend - tstart
    
    tstart = time.perf_counter()
    session.write_pandas(output, 'OUTPUT_PANDAS', overwrite=True, chunk_size=1000000, compression='snappy')
    tend = time.perf_counter()
    tout = tend - tstart
        
    return json.dumps(dict(rows=len(output),
                           tloadtrades=tloadtrades,
                           tloadquotes=tloadquotes,
                           tpdalgo=tpdalgo,
                           tout=tout))

The version of package numpy in the local environment is 1.24.2, which does not fit the criteria for the requirement numpy. Your UDF might not work when the package version is different between the server and your local environment

CPU times: user 36.8 ms, sys: 0 ns, total: 36.8 ms
Wall time: 26.8 s

In [9]:
%%time

rez = my_pandas_procedure()
rez = json.loads(rez)
rez

CPU times: user 480 ms, sys: 128 ms, total: 608 ms
Wall time: 1h 10min 56s

{'rows': 77026358,
 'tloadtrades': 58.051440508999804,
 'tloadquotes': 1228.2382535439992,
 'tpdalgo': 2842.166595957,
 'tout': 125.41016308399958}

In [10]:
%%time

@sproc(packages=['snowflake-snowpark-python', 'numpy', 'pandas', 'pyarrow'],
       imports=['@~/kx/pykx-package.zip', '@~/kx/01_interval_returns.q_'])
def my_pykx_procedure(session: Session) -> str:
    import base64, json, os, shutil, sys, time, zipfile
   
    ## CUSTOM SETUP OF PyKX (won't be needed when PyKX is available on Anaconda)
    tstart = time.perf_counter()
    if not os.path.exists('/tmp/k4.lic'):
        import_dir = sys._xoptions.get("snowflake_import_directory")
        lib = 'pykx-package.zip'
        lib_path = os.path.join(import_dir, lib)
        load_path = '/tmp/pykx-package/'

        if os.path.exists('/tmp/pykx-package'):
            shutil.rmtree('/tmp/pykx-package')
            time.sleep(0)
        with zipfile.ZipFile(lib_path, 'r') as zip_ref:
            zip_ref.extractall('/tmp/pykx-package')

        sys.path.insert(0, '/tmp/pykx-package')
        
        shutil.copyfile(os.path.join(import_dir, '01_interval_returns.q_'), '/tmp/01_interval_returns.q_')

        with open('/tmp/k4.lic', 'wb') as f:
            f.write(base64.b64decode(license))
    tend = time.perf_counter()
    tpykxinstall = tend - tstart
    ## END

    tstart = time.perf_counter()
    os.environ['QHOME'] = ''
    os.environ['QLIC'] = '/tmp'

    os.environ['PYKX_LOAD_PYARROW_UNSAFE'] = '1'
    os.environ['PYKX_NOQCE'] = '1'
    os.environ['SKIP_UNDERQ'] = '1'
    os.environ['IGNORE_QHOME'] = '1'
    os.environ['QARGS'] = '--licensed'
    
    import pykx as kx
    tend = time.perf_counter()
    tpykximport = tend - tstart
    
    tstart = time.perf_counter()
    select_columns = ['"TTime"', '"Symbol"', '"Trade Volume"', '"Trade Price"']
    trades = session.table('trades').select(select_columns).order_by('"TTime"').to_pandas()
    trades.columns = ['time', 'symbol', 'volume', 'price']
    tend = time.perf_counter()
    tloadtrades = tend - tstart
    
    tstart = time.perf_counter()
    kx.q['trades'] = trades
    del trades
    tend = time.perf_counter()
    ttoqtrades = tend - tstart

    tstart = time.perf_counter()
    select_columns = ['"TTime"', '"Symbol"', '"Bid_Size"', '"Bid_Price"', '"Offer_Size"', '"Offer_Price"']
    quotes = session.table('quotes').select(select_columns).order_by('"TTime"').to_pandas()
    quotes.columns = ['time', 'symbol', 'ask_volume', 'ask_price', 'bid_volume', 'bid_price']
    tend = time.perf_counter()
    tloadquotes = tend - tstart
    
    tstart = time.perf_counter()
    kx.q['quotes'] = quotes
    del quotes
    tend = time.perf_counter()
    ttoqquotes = tend - tstart

    tstart = time.perf_counter()
    kx.q('\l /tmp/01_interval_returns.q_')  # Run a locked q script to apply the business logic
    tend = time.perf_counter()
    tqalgo = tend - tstart
    
    tstart = time.perf_counter()
    output = kx.q('t').pd()
    tend = time.perf_counter()
    ttopd = tend - tstart
    
    tstart = time.perf_counter()
    session.write_pandas(output, 'OUTPUT', overwrite=True, chunk_size=1000000, compression='snappy')
    tend = time.perf_counter()
    tout = tend - tstart
    
    return json.dumps(dict(rows=len(output),
                           tpykxinstall=tpykxinstall,
                           tpykximport=tpykximport, 
                           tloadtrades=tloadtrades,
                           tloadquotes=tloadquotes,
                           ttoqtrades=ttoqtrades,
                           ttoqquotes=ttoqquotes,
                           tqalgo=tqalgo,
                           ttopd=ttopd,
                           tout=tout))

The version of package numpy in the local environment is 1.24.2, which does not fit the criteria for the requirement numpy. Your UDF might not work when the package version is different between the server and your local environment

CPU times: user 78.6 ms, sys: 8.44 ms, total: 87 ms
Wall time: 8.15 s

In [11]:
%%time

rez = my_pykx_procedure()
rez = json.loads(rez)
rez

CPU times: user 202 ms, sys: 29.7 ms, total: 232 ms
Wall time: 26min 58s

{'rows': 77026358,
 'tpykxinstall': 0.08213187299952551,
 'tpykximport': 0.09185756300030334,
 'tloadtrades': 54.13278269999864,
 'tloadquotes': 1085.171100691001,
 'ttoqtrades': 14.336428853999678,
 'ttoqquotes': 295.7157443670003,
 'tqalgo': 34.38230798699988,
 'ttopd': 3.74148608699943,
 'tout': 127.1753651809995}